# version: '3.8'  # Removed as it's obsolete

services:
  postgres:
    image: postgres:15-alpine
    container_name: futa-postgres
    environment:
      POSTGRES_DB: futa_students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: futa-students-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: futa_students
      DB_USER: postgres
      DB_PASSWORD: postgres123
      NODE_ENV: production
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./frontend:/app/frontend

volumes:
  postgres_data: