# version: '3.8'  # Removed as it's obsolete

services:
  postgres:
    image: postgres:15-alpine
    container_name: futa-postgres
    environment:
      POSTGRES_DB: futa_students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app1:
    build: .
    container_name: futa-students-app1
    ports:
      - "8081:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: futa_students
      DB_USER: postgres
      DB_PASSWORD: postgres123
      NODE_ENV: production
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy

  app2:
    build: .
    container_name: futa-students-app2
    ports:
      - "8082:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: futa_students
      DB_USER: postgres
      DB_PASSWORD: postgres123
      NODE_ENV: production
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: futa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2

volumes:
  postgres_data: