name: FUTA Student API CI

on:
  push:
    paths:
      - 'src/**'
      - 'frontend/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'frontend/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Build API
      run: make run-api
      
    - name: Perform code linting
      run: make lint
      
    - name: Run tests
      run: make test
      
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/futa-students-api:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/futa-students-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/futa-students-api:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/futa-students-api:latest